name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
variables:
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/DrCadair/test/_build/results?buildId=$(Build.BuildId)"
  CIBW_BUILD: cp36-* cp37-*
  CIBW_SKIP: "*-win32 *-manylinux1_i686"

# These resources need to be setup on the Azure Pipeline website
# as a service connection (if it has not been already).
resources:
  repositories:
  - repository: sunpy
    type: github
    endpoint: Cadair
    name: sunpy/azure-pipelines-template
    ref: pypi_no_wheels

jobs:

- template: publish.yml@sunpy
  parameters:
    targets:
        - wheels_linux
        - wheels_macosx
        - wheels_windows
        - sdist
    artifact_feed: 'test'
    pypi_remote: 'test'

